### ISSUE TITLE
TypeError: Cannot read property 'headers' of undefined

### ISSUE THREAD

**Issue by matthias-g** [import-io/client-js-mini#3]
Using this library my app sometimes crashes with the following error:

```
/path/to/app/node_modules/import-io/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:208
      && response.headers[header.toLowerCase()]
                 ^
TypeError: Cannot read property 'headers' of undefined
    at getResponseHeader (/path/to/app/node_modules/import-io/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:208:18)
    at xhr.onreadystatechange (/path/to/app/node_modules/import-io/importio.js:109:25)
    at dispatchEvent (/path/to/app/node_modules/import-io/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:570:25)
    at setState (/path/to/app/node_modules/import-io/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:589:14)
    at handleError (/path/to/app/node_modules/import-io/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:514:5)
    at ClientRequest.errorHandler (/path/to/app/node_modules/import-io/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:439:14)
    at ClientRequest.emit (events.js:95:17)
    at CleartextStream.socketCloseListener (http.js:1526:9)
    at CleartextStream.emit (events.js:95:17)
    at tls.js:693:10
```

This happens irregularly after being connected to import-io. It doesn't matter whether queries were already run.

**Comment by martinpfannemueller** [comment]
I encounter exactly the same problem. I can confirm that it happens irregularly. For now always some queries have been run.
